### ISSUE TITLE
Sudden failure to complete processing...

### ISSUE THREAD

**Issue by frankrue** [Wildhoney/gulp-processhtml#15]
Hello! I just pulled a boilerplate repository that uses this package and it suddenly stopped building.

The error I'm getting is this:

```bash
TypeError: Cannot read property 'customBlockTypes' of undefined
    at module.exports (/Users/frue/gits/base2/node_modules/gulp-processhtml/index.js:8:17)
    at Gulp.<anonymous> (/Users/frue/gits/base2/gulpfile.js:81:11)
    at module.exports (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/frue/gits/base2/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

You can also take a look at my boilerplate project here: [base2](https://github.com/frankrue/base2).

I'm not sure why this is suddenly breaking and believing that I have a customBlockType—I am not using them. My options hash was empty previously: `processhtml()`. 

Thoughts?

**Comment by frankrue** [comment]
Also, I found that your tags here (github.com) are 1.0.3 and 1.0.4. The NPM packages list 1.0.5 as the latest version, but the ACTUAL previous version appears to be 1.0.2. This is very confusing—I'm not sure if it can all be edited to be consistent. 

Basically, as soon as I went back to v1.0.2, everything worked again.

**Comment by red2678** [comment]
Same issue here still. Do I need to downgrade?

**Comment by fergaldoyle** [comment]
Also had to revert to 1.0.2 and lock down to that version in package.json. e.g. changing `"gulp-processhtml": "^1.0.2"` to `"gulp-processhtml": "^1.0.2"`.  

Significant changes should increment the major or minor number not the patch number. 

Looking at the source, options is not longer optional. You must pass in an object to the function otherwise it tries to access properties of undefined. Even if you pass in an options object, `'./custom/replace.js'` not found.

**Comment by Wildhoney** [comment]
Should be fixed now thanks to @rblopes [pull request](https://github.com/Wildhoney/gulp-processhtml/pull/16). Sorry about this!

**Comment by red2678** [comment]
:+1:
